services:
  db:
    image: postgres:15-alpine
    container_name: skysecure_db
    environment:
      POSTGRES_USER: skysecure_user
      POSTGRES_PASSWORD: skysecure_password
      POSTGRES_DB: skysecure_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DataBase:/docker-entrypoint-initdb.d:ro  
    restart: unless-stopped

  backend:
    image: python:3.10-slim
    container_name: skysecure_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    working_dir: /app
    # Instalowanie bibliotek i uruchamianie aplikacji FastAPI
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: skysecure_proxy
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./FrontEnd:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata: