CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE Uzytkownicy (
    id_uzytkownika INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nazwisko VARCHAR(50) NOT NULL,
    imie VARCHAR(30) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    haslo_hash VARCHAR(255) NOT NULL,
    rola VARCHAR(20) NOT NULL DEFAULT 'User',
    data_rejestracji TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);